export const AUDITORIA_ACOES = Object.freeze({

    CRIAR_ESPECIE: 'CRIAR_ESPECIE',
    ATUALIZAR_ESPECIE: 'ATUALIZAR_ESPECIE',
    INATIVAR_ESPECIE: 'INATIVAR_ESPECIE',

    CRIAR_MOVIMENTACAO: 'CRIAR_MOVIMENTACAO',
    ESTORNAR_MOVIMENTACAO: 'ESTORNAR_MOVIMENTACAO',

    CRIAR_LOTE: 'CRIAR_LOTE',
    ATUALIZAR_FASE_LOTE: 'ATUALIZAR_FASE_LOTE',
    TRANSFERIR_LOTE: 'TRANSFERIR_LOTE',
    CANCELAR_LOTE: 'CANCELAR_LOTE',
    REGISTRAR_MORTALIDADE: 'REGISTRAR_MORTALIDADE',

    CRIAR_ESTUFA: 'CRIAR_ESTUFA',
    ATUALIZAR_ESTUFA: 'ATUALIZAR_ESTUFA',
    INATIVAR_ESTUFA: 'INATIVAR_ESTUFA',

    CRIAR_USUARIO: 'CRIAR_USUARIO',
    ATUALIZAR_USUARIO: 'ATUALIZAR_USUARIO',
    INATIVAR_USUARIO: 'INATIVAR_USUARIO',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    ATIVAR_CONTA: 'ATIVAR_CONTA',
    RESETAR_SENHA: 'RESETAR_SENHA',

    CRIAR_DESTINATARIO: 'CRIAR_DESTINATARIO',
    ATUALIZAR_DESTINATARIO: 'ATUALIZAR_DESTINATARIO',
    INATIVAR_DESTINATARIO: 'INATIVAR_DESTINATARIO',

    EXPEDIR_LOTE: 'EXPEDIR_LOTE',
});

export const AUDITORIA_ENTIDADES = Object.freeze({
    ESPECIE: 'Especie',
    MOVIMENTACAO: 'Movimentacao',
    LOTE: 'Lote',
    ESTUFA: 'Estufa',
    USUARIO: 'Usuario',
    DESTINATARIO: 'Destinatario',
});